seed: 0
version: jhu_fog2snow_ibn3
device: 'cuda:0'
log_para: 1000
patch_size: 1440
mode: 'simple'
num_epochs: &num_epochs 80
checkpoint: /mnt/home/zpengac/USERDIR/Crowd_counting/DGVCC/logs/jhu_fog2snow_ibn3/best_66_57.1766.pth
model:
  name: 'ibn'
  params:
    pretrained: True
train_dataset: &train_dataset_params
  name: 'jhu_domain_cls'
  params: 
    root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/jhu'
    domain_label: 'jhu_fog'
    domain_type: 'weather'
    domain: 3
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 16
    pre_resize: 1
val_dataset: *train_dataset_params
test_dataset:
  name: 'jhu_domain_cls'
  params: 
    root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/jhu'
    domain_label: 'jhu_snow'
    domain_type: 'weather'
    domain: 1
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 16
    pre_resize: 1
train_loader:
  batch_size: 16
  num_workers: 16
  shuffle: True
  pin_memory: True
val_loader: &val_loader_params
  batch_size: 1
  num_workers: 4
  shuffle: False
  pin_memory: False
test_loader: *val_loader_params
loss:
  name: 'mse'
  params:
    reduction: 'mean'
optimizer:
  name: 'adamw'
  params:
    lr: &lr 0.001
    weight_decay: 0.0001
scheduler:
  name: 'onecycle'
  params:
    max_lr: *lr
    epochs: *num_epochs
    steps_per_epoch: 13
    final_div_factor: 1000