seed: 1293
version: sta_isw_new4
device: 'cuda:0'
log_para: 1000
patch_size: 1440
mode: 'isw'
num_epochs: &num_epochs 120
checkpoint: /mnt/home/zpengac/USERDIR/Crowd_counting/DGVCC/logs/sta_isw_new4/best_74_95.2208.pth
model:
  name: 'isw'
  params:
    variant: 'D'
    skip: 'm1'
    skip_num: 48
train_dataset: &train_dataset_params
  name: 'den_cls'
  params: 
    root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/sta'
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 16
    pre_resize: 1
val_dataset: *train_dataset_params
test_dataset:
  name: 'den_cls'
  params: 
    root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/stb'
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 16
    pre_resize: 1
train_loader:
  batch_size: 16
  num_workers: 16
  shuffle: True
  pin_memory: True
val_loader: &val_loader_params
  batch_size: 1
  num_workers: 4
  shuffle: False
  pin_memory: False
test_loader: *val_loader_params
loss:
  name: 'mse'
  params:
    reduction: 'mean'
optimizer:
  name: 'adamw'
  params:
    lr: &lr 0.001
    weight_decay: 0.0001
scheduler:
  name: 'onecycle'
  params:
    max_lr: *lr
    epochs: *num_epochs
    steps_per_epoch: 15
    final_div_factor: 1000