seed: 2112
method: Density
mode: REGRESSOR
num_epochs: &num_epochs 300
batch_size: 32
num_workers: 16
log_para: 1000
version: sta_reg_mem_noresize
model:
  style_dim: 64
  pretrained: True
train_dataset:
  root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/sta'
  crop_size: 320
  downsample: 1
  is_grey: False
  unit_size: 16
  pre_resize: 1
  # gen_root: '/mnt/home/zpengac/USERDIR/Crowd_counting/DGVCC/logs/sta_joint_newmem3_2/gen'
test_dataset:
  root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/qnrf'
  crop_size: 320
  downsample: 1
  is_grey: False
  unit_size: 16
  pre_resize: 1
optimizer:
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  step_size: 1
  gamma: 0.995