seed: 2112
method: Density
mode: AUGMENTED
num_epochs: &num_epochs 100
batch_size: 8
num_workers: 16
log_para: 1000
version: sta_augmented_onlynoval2
model:
  style_dim: 64
  pretrained: True
train_dataset:
  root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/sta'
  crop_size: 320
  downsample: 1
  is_grey: False
  unit_size: 16
  pre_resize: 1
test_dataset:
  root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/stb'
  crop_size: 320
  downsample: 1
  is_grey: False
  unit_size: 16
  pre_resize: 1
optimizer:
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  step_size: 1
  gamma: 0.995