seed: 2112
version: sta_gen
device: 'cuda:0'
mode: generation
log_para: 1000
method: Density
num_epochs: &num_epochs 300
checkpoint: null
model:
  name: 'dgnet'
  params:
    pretrained: True
train_dataset: &train_dataset_params
  name: 'den'
  params: 
    root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/sta'
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 16
    pre_resize: 1
val_dataset: *train_dataset_params
test_dataset:
  name: 'den'
  params: 
    root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/stb'
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 16
    pre_resize: 1
loss:
  name: 'mse'
  params:
    reduction: 'mean'
optimizer:
  name: 'adamw'
  params:
    lr: 0.0001
    weight_decay: 0.0001
scheduler:
  name: 'step'
  params:
    step_size: 1
    gamma: 0.995


optimizer:
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  step_size: 1
  gamma: 0.995