seed: 2112
method: Density
mode: REGRESSOR
num_epochs: &num_epochs 120
batch_size: 32
num_workers: 16
log_para: 1000
version: ucsd_augmented
model:
  style_dim: 64
  pretrained: True
train_dataset:
  root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/ucsd3'
  crop_size: 128
  downsample: 1
  is_grey: False
  unit_size: 16
  pre_resize: 1
  # roi_map_path: '/mnt/data/smartcity/ucsd/train/roi/perspective_roi.npy'
  gen_root: '/mnt/home/zpengac/USERDIR/Crowd_counting/DGVCC/logs/ucsd_joint/gen'
test_dataset:
  root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/mall'
  crop_size: 128
  downsample: 1
  is_grey: False
  unit_size: 16
  pre_resize: 1
optimizer:
  lr: 0.0001
  weight_decay: 0.0001
scheduler:
  step_size: 1
  gamma: 0.995