seed: 2112
version: sta_joint_mem8
device: 'cuda:2'
log_para: 1000
mode: 'joint'
num_epochs: &num_epochs 100
checkpoint:
  - '/mnt/home/zpengac/USERDIR/Crowd_counting/DGVCC/logs/sta_gen/best_295_0.0273.pth'
  - '/mnt/home/zpengac/USERDIR/Crowd_counting/DGVCC/logs/sta_reg_mem/best_63_102.1207.pth'
model:
  name: 'dgnet'
  params:
    pretrained: True
train_dataset: &train_dataset_params
  name: 'den_cls'
  params: 
    root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/sta'
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 32
    pre_resize: 1
val_dataset: *train_dataset_params
test_dataset:
  name: 'den_cls'
  params: 
    root: '/mnt/home/zpengac/USERDIR/Crowd_counting/datasets/stb'
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 32
    pre_resize: 1
train_loader:
  batch_size: 4
  num_workers: 16
  shuffle: True
  pin_memory: True
val_loader: &val_loader_params
  batch_size: 1
  num_workers: 4
  shuffle: False
  pin_memory: False
test_loader: *val_loader_params
loss:
  name: 'mse'
  params:
    reduction: 'mean'
optimizer:
  name: 'adamw'
  params:
    lr: &lr 0.001
    weight_decay: 0.0001
scheduler:
  name: 'onecycle'
  params:
    max_lr: *lr
    epochs: *num_epochs
    steps_per_epoch: 60